"""empty message

Revision ID: 68b2a1c98819
Revises: 0891006f2a0f
Create Date: 2020-04-02 06:04:40.829702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68b2a1c98819'
down_revision = '0891006f2a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face', 'meta_data')
    # ### end Alembic commands ###
