"""empty message

Revision ID: 92dd054dffc1
Revises: 01faca18f168
Create Date: 2020-03-11 07:05:31.964571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dd054dffc1'
down_revision = '01faca18f168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('face_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face', 'face_id')
    # ### end Alembic commands ###
